services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        SITE_URL: http://localhost:3000
        API_URL: http://backend:8080
    restart: always
    ports:
      - 3000:3000
    networks:
      - my_network
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/dashboard?sslmode=disable
      - JWT_SECRET=superbank_test
      - PORT=8080
    depends_on:
      - db
    networks:
      - my_network
    volumes:
      - ./backend:/app

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dashboard
    networks:
      - my_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge
